### ISSUE TITLE
Setting up a nightly job to do database maintenance/index updating

### ISSUE THREAD

**Issue by rgerkin** [neuroelectro/neuroelectro_org#1]
Use case: when a user adds an article with ephys data, we add that data to the database, but we don't update corresponding "Summary" database fields, like NeuronSumary or EphysPropSummary. While it's possible to rerun these scripts every time a user adds data, this is probably overkill.

I think a better solution is to just run a script every night or every weekend updating these fields.

---------------------------------------
- Bitbucket: https://bitbucket.org/rgerkin/neuroelectro_org/issue/1
- Originally Reported By: [Shreejoy Tripathy](http://bitbucket.org/shreejoy)
- Originally Created At: 2014-06-19T22:19:03.861

**Comment by stripathy** [comment]
To have scripts run nightly using cron on the neuroelectro dev and production machines, do the following:

1) add your script to /scripts (follow these instructions (http://django-extensions.readthedocs.org/en/latest/runscript.html)
2) add your script to the global bash script file, db_update_script.sh in the neuroelectro_org base directory, using the following: "python manage.py runscript <scriptname>"
