### ISSUE TITLE
Create a basic "test suite" for article full text text-mining

### ISSUE THREAD

**Issue by rgerkin** [neuroelectro/neuroelectro_org#10]
Come up with a basic set of tests to validate basic functionality for article text mining algorithms.

The goal here is to check the "parsing" or "extracting" functionality and make sure that updates to the text-mining code does not break existing functionality.

---------------------------------------
- Bitbucket: https://bitbucket.org/rgerkin/neuroelectro_org/issue/10
- Originally Reported By: [Shreejoy Tripathy](http://bitbucket.org/shreejoy)
- Originally Created At: 2014-07-11T23:05:39.453

**Comment by stripathy** [comment]
implemented in 4cd132221dc51a97bf06dd50bed5685c4813668f
