### ISSUE TITLE
data table ephys parsing failed for this table

### ISSUE THREAD

**Issue by stripathy** [neuroelectro/neuroelectro_org#136]
http://dev.neuroelectro.org/data_table/23070/

**Comment by stripathy** [comment]
and this one: http://dev.neuroelectro.org/data_table/3332/

**Comment by stripathy** [comment]
http://dev.neuroelectro.org/data_table/812/

**Comment by dtebaykin** [comment]
http://dev.neuroelectro.org/data_table/24554/

Not all nedm's were created based on the NT vs ephys curations

**Comment by stripathy** [comment]
http://dev.neuroelectro.org/data_table/24554/

**Comment by stripathy** [comment]
http://dev.neuroelectro.org/data_table/22272/

**Comment by stripathy** [comment]
http://dev.neuroelectro.org/data_table/812/
