### ISSUE TITLE
write some very basic tests for ephys unit coversion code

### ISSUE THREAD

**Issue by stripathy** [neuroelectro/neuroelectro_org#155]

**Comment by rgerkin** [comment]
Why not use something like the `quantities` package in Python?

**Comment by stripathy** [comment]
Good idea, I decided to use the python package Pint for unit conversion
since it seemed to be a bit better with parsing units out from strings.

@rgerin feel free to review the tests that I wrote:
https://github.com/neuroelectro/neuroelectro_org/blob/master/tests/test_unit_conversion.py

**Comment by rgerkin** [comment]
If you use `quantities` you will be ready for `neo` or `elephant` conversion in the future.  I'm curious: where was `quantities` failing with parsing from strings?  Generally I have found that `quantities.Quantity(numeric_value,unit_string)` always works.

**Comment by stripathy** [comment]
We're not storing any of the Pint quantites in the neuroelectro DB, we're
just using it on the backend for unit conversion.

What I liked about Pint was that it seemed to support more variations on
'''unit_string''' than quantitites, essentially doing the unit string
normalization for me.
