### ISSUE TITLE
Make article metadata curation more interactive

### ISSUE THREAD

**Issue by dtebaykin** [neuroelectro/neuroelectro_org#157]

**Comment by dtebaykin** [comment]
Article level metadata needs the following features:
1) Curation history (iframe similar to table curation interface) attached to the metadata name. (Make the meta name a clickable link or button)
2) Curator note - a text field under each metadata value selection field.

**Comment by stripathy** [comment]
1) is on the way, slowly.
2) is implemented.

I'm making a new issue for 1) and then closing this issue.
