### ISSUE TITLE
Metadata curation interface bugs

### ISSUE THREAD

**Issue by dtebaykin** [neuroelectro/neuroelectro_org#185]
1) mm must be present or bust, change this to parse solution sentence anyway.
2) convert m to mm somehow
3) conc values might be in brackets, fix the recognition code for nums
4) fix guidelines (Shreejoy): don't record N if it is already in nedms
5) add a link from metadata page back to table curation interface

**Comment by dtebaykin** [comment]
Add "not mentioned" option to junction potential drop down.

**Comment by dtebaykin** [comment]
Make sure K-acetate 3000 mm is parsed into a soln conc.

**Comment by dtebaykin** [comment]
Resolve spike overshoot and spike amplitude, add new ephys properties to the list.

**Comment by dtebaykin** [comment]
Build:  9002af8
1) Fixed
2) Fixed (tentatively - as more cases of Moles usage reported, enhance the regex)
3) This should be working, need to see where this is failing

7) K-acetate 3000 mm is parsed properly now

**Comment by stripathy** [comment]
more additions to add:
Add:
Hartley to Strains
Unobserved to JxnPotential
- vs long - in solution mining
