### ISSUE TITLE
convert solution values reported in mole not millimole

### ISSUE THREAD

**Issue by stripathy** [neuroelectro/neuroelectro_org#187]
@dtebaykin we can work on this together, I added 'M' as a common synonym for moles for the unit conversion

**Comment by dtebaykin** [comment]
I have already fixed this in the code during the parsing - the units don't get parsed out of the string since very often they just say (in mm) once at the beginning of the solution reporting.

**Comment by dtebaykin** [comment]
Add a conversion from nm and micro-moles into mm

**Comment by dtebaykin** [comment]
done
