### ISSUE TITLE
Script needed: re-parse curated solutions

### ISSUE THREAD

**Issue by dtebaykin** [neuroelectro/neuroelectro_org#192]
Textmining code is being updated, so it needs to be rerun not just on the text-mined articles, but also on already curated ones where the solution sentences have been identified by the curators.

The script should run the concentration extraction part on the solutions with the curated flag of 5.0

**Comment by stripathy** [comment]
needs to be reperformed upon text-mining code improvements to solutions

**Comment by dtebaykin** [comment]
This is now part of the nightly NeuroElectro database scripts run - it re-textmines the uncurated articles.
Part 2: re-extract numbers from the already curated sentences. Work in progress.
