### ISSUE TITLE
Add thresholds for ephys properties and flag bad data

### ISSUE THREAD

**Issue by rgerkin** [neuroelectro/neuroelectro_org#20]
In the models.py class add a flag field to each ephys. property that would be based on where the value for that property fits with respect to threshold values, i.e.:

Vm > 0 mV or Vm < -100 mV could be red flag

Consider adding multiple threshold checks (orange, yellow, green).
Green threshold values could be calculated based on the average value (and average error) for other (perhaps already curated) articles of that same neuron type (or superfamily).

---------------------------------------
- Bitbucket: https://bitbucket.org/rgerkin/neuroelectro_org/issue/20
- Originally Reported By: [Dmitry Tebaykin](http://bitbucket.org/dtebaykin)
- Originally Created At: 2014-08-15T20:34:43.602

**Comment by stripathy** [comment]
implemented (at least initially) in commit: 783706c18f974976ae2968b8cb6fbfa59a4259ea
