### ISSUE TITLE
explicitly search for creatine or phosphocreatine in solutions mining

### ISSUE THREAD

**Issue by stripathy** [neuroelectro/neuroelectro_org#211]
from Jim Berg: One other thing that we noticed in some papers is that they just say 10 phosphocreatine but they don’t mention the cation – I’ll bet those are sodium salts.
Another way of mentioning this solution component is to say "creatine phosphate"

**Comment by dtebaykin** [comment]
Na-phosphocreatine and sodium phosphocreatine now get parsed as Na2-phosphocreatine correctly, but the deeper problem remains: 10 phosphocreatine needs to be treated as 10 Na2-pho, but di(Tris)-pho, K2-pho and the rest should not be added to Na concentration.

**Comment by stripathy** [comment]
How prevalent is the case of phosophocreatine vs sodium phosphocreatine vs
(not Na) phosphocreatine?

**Comment by dtebaykin** [comment]
From ~200 internal solutions, 51 contained "creatine", out of those about 40% are just "phosphocreatine", the rest are Tris-pho or Na-pho. I am going to treat "pho" as Na-pho and ignore Tris-pho for now.
