### ISSUE TITLE
clean up broken links for user/curation contributions

### ISSUE THREAD

**Issue by stripathy** [neuroelectro/neuroelectro_org#255]

**Comment by JustasB** [comment]
I hope the following are already known issues:

1) When I click "Report Miscurated Data" on http://neuroelectro.org/article/37352/, fill out the form, and submit, I get a page unavailable error. Can't tell if the form data went through.

2) After signing up with Google, then going to http://neuroelectro.org/contribute/, clicking "Contribute Neuron Data", submitting the pubmed search box, results in error: "The http://entrezajax.appspot.com service we rely on for displaying texts appears to be unavailable at this time. Please try again later."

3) Continuing to fill out the form in #2, clicking submit also results in a "page unavailable" error.

**Comment by stripathy** [comment]
Thanks @JustasB , I knew about the second issue you raised but not the first. I'll fix both of these soon.

Were you hoping to use the contribute neuron data feature?

**Comment by JustasB** [comment]
Thanks @stripathy! I was. This is what I wanted to add:

I was trying to report the spontaneous firing rate value for article: http://neuroelectro.org/article/37352/. The value can be found in the full text ( http://www.jneurosci.org/content/21/14/5311.long ) by searching: "The mean rate of spontaneous action potential generation for bistable mitral cells was 2.95 ± 0.25 Hz"

**Comment by stripathy** [comment]
Great, thanks @JustasB. The feature has been broken for a while or so (it was relying on another package for querying pubmed, entrezajax https://github.com/nickloman/entrezajax, which has since stopped working) and we haven't removed the feature. I'll do the following: remove the feature from the base neuroelectro.org website. This doesn't solve your problem but at least it doesn't expose broken features to the naive user. 

@JustasB I'll get back to you once I do this and then we can figure out how to add that piece of data correctly to the database. Thanks so much for pointing this out to us!

**Comment by JustasB** [comment]
Sure no probs
