### ISSUE TITLE
Neuroelectro website UI overhaul

### ISSUE THREAD

**Issue by dtebaikin** [neuroelectro/neuroelectro_org#29]
Shreejoy has been receiving comments that it is sometimes hard to find the information users are interested in. Moreover, it is hard to understand whether said information is present in Neuroelectro at all.

So, we need to outline the websites use cases for different types of users and provide better navigation options, convey what information they would be able to find on the website.

Matt from Pavlidis lab is a UI design expert - collaborate for some basic pointers.

**Comment by stripathy** [comment]
I've put some effort into this by just cleaning up the navigation bar. I think this goes a long way towards this, but getting more feedback on this would be good.
