### ISSUE TITLE
update storage location of full texts on kent server

### ISSUE THREAD

**Issue by stripathy** [neuroelectro/neuroelectro_org#304]
need help on this from @dtebaykin

**Comment by dtebaykin** [comment]
What is the issue here?

**Comment by stripathy** [comment]
The full texts are being stored locally on kent but we're almost at
capacity for the HDs on kent. I need to update the location where the full
texts are stored and then update the DB references. Do you know how to do
this?

On Sat, Jun 4, 2016 at 1:43 PM Dmitry Tebaykin <notifications@github.com>
wrote:

> What is the issue here?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/neuroelectro/neuroelectro_org/issues/304#issuecomment-223777277>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACWEWfKgcgJyN2wKGPDMZLyO3iUPGGPKks5qIeOBgaJpZM4IuNZ9>
> .
>
-- 
Shreejoy Tripathy
Post-Doctoral Researcher
Department of Psychiatry
University of British Columbia

**Comment by dtebaykin** [comment]
We can look into this on Monday

**Comment by stripathy** [comment]
This seems easy enough to do by adding a MEDIA_ROOT field in each server's local settings and updating with the new file path
