### ISSUE TITLE
Age and Temperature metadata

### ISSUE THREAD

**Issue by dtebaykin** [neuroelectro/neuroelectro_org#32]
Check why age and temperature are not always picked up by the text-mining script from the methods section (possibly due to methods section not being discoverable).

Example: 
http://www.neuroelectro.org/article/11874/metadata/

Article:
http://onlinelibrary.wiley.com/doi/10.1111/j.1460-9568.2006.04733.x/full
"To test whether progressive Aβ accumulation disrupts synaptic plasticity at excitatory synapses in the neocortex, parasagittal cortical slices (300 µm) were prepared from male APPswe/PS1dE9 mice aged 3.5 and 7 months"

**Comment by dtebaykin** [comment]
Kris has a spreadsheet of LTP values with all the metadata - most of those articles do not have temperature or age values. The sheet will be uploaded to Team Neuroelectro dropbox and studied.

**Comment by stripathy** [comment]
Closing this since newly processed articles seem to have these metadata found (but not always)
