### ISSUE TITLE
set up pip install neuroelectro script

### ISSUE THREAD

**Issue by stripathy** [neuroelectro/neuroelectro_org#35]
Installing neuroelectro from github currently is quite difficult due to package dependencies. A simple install script would make this much easier.

**Comment by stripathy** [comment]
Marking this as closed, since the setup scripts that @dtebaykin and @mgottl04 put together are basically this.

**Comment by rgerkin** [comment]
@stripathy I think it would be good to do this anyway, because in the process you create a setup.py, which handles all the dependencies in a reliable way.

**Comment by rgerkin** [comment]
In the long run, I imagine the basic setup.py would not actually install the database locally, but set things up to use the API by default.  Then some flag or warning message would direct the user to local scripts that get the database setup.  More in #55

**Comment by stripathy** [comment]
@rgerkin - is putting together the base pip install neuroelectro script something you can help with? I'm still not sure how to nicely get around the need for the database issue though - without doing what you proposed and replacing all DB calls with API calls.

**Comment by dtebaykin** [comment]
I think we could include a .sql dump file into the repository and then in the pip install script we can have the following lines of code: 
'''
echo "create database neuroelectro" | mysql -u root -p
mysql -u root -p neuroelectro < neuroelectro_dumpfile.sql
'''
There are still things we will not be able to automate, for example, editing the local_settings.py file as well as other things I am probably forgetting at the moment. In spite of that we should have 2 files for installation: one pip install script and a README file that would have all of the steps the user themselves have to take in great detail.

**Comment by rgerkin** [comment]
@stripathy @dtebaykin In order to do this safely, this whole repo needs to have the neuroelectro.org content separated from the neuroelectro scraping/analyzing/parsing stuff.  Also see #74.

**Comment by stripathy** [comment]
Based on a conversation with @rgerkin - this command should do the following
1. pull the most up-to-date working code from github onto the user's local machine
2. pull a slimmed version of the neuroelectro DB locally and install it as a sqllite file (since this is much easier to control for the naive user than asking them to install a mysql file)
3. pull some basic analysis functions and a python API to make working with the neuroelectro DB easier than it is currently (i.e., ```neuroelectro.models.Neuron.objects.all()``` should be ```neuroelectro.get_neurons```)

Things remaining to be specified: 
1. which code should get pulled vs which should not?
2. just how much of the DB should get pulled? maybe a 'slim' DB with just the curated content.
3. developing the python API to the neuroelectro DB
