### ISSUE TITLE
Create ExperimentalFactor model

### ISSUE THREAD

**Issue by dtebaykin** [neuroelectro/neuroelectro_org#36]
Main idea: We want to store the experimental factors that are varied from control to treated samples on a data entry to data entry level instead of the whole article level (as the current Metadata model does it).

This task involves the following steps:
1) Create ExpFactorConceptMap which would be similar to EphysConceptMap and NeuronConceptMap - it will link entries in article data tables to the metadata that is applicable only to the specific entries.
2) ExpFactor table will contain the actual experimental factors from the table rows/columns. This table will be very similar to Metadata model in NeuroElectro.

**Comment by stripathy** [comment]
Below is my implementation of this: I decided for the `ExpFactConceptMap` class to link out to the existing `MetaData` class (as opposed to creating a new `ExpFact` class which mostly duplicates `MetaData`) for now for simplicity. We can revisit this decision later when we need to (e.g., when we start incorporating Gene knock outs as experimental factors and if we want to keep this separate from `MetaData`.
Existing implementation:
```python
class ExpFactConceptMap(ConceptMap):
    metadata = models.ForeignKey('MetaData')
    
    def __unicode__(self):
        return u'%s %s' % (self.ref_text.encode("iso-8859-15", "replace"), self.metadata)
```
