### ISSUE TITLE
Add tracking of user validations for modification of article-level metadata

### ISSUE THREAD

**Issue by stripathy** [neuroelectro/neuroelectro_org#51]

**Comment by stripathy** [comment]
From talking to @dtebaykin - I realized that we need to rethink the current workflow. At what point is the data "validated"? When a user edits an entry in a table? or when they hit the "validate all" button?

**Comment by rgerkin** [comment]
@stripathy I think a user having edited a single cell should validate the content of that cell.  Any other data should be considered unvalidated unless the user explicitly clicks something to indicate validation of the whole table.  You should then track the number and identity of validators for each cell (for each nedms), and "validate all" should append the identity of the validator with all the cells.

**Comment by stripathy** [comment]
the main work to be done here is migrating the old way we were tracking user curations to the new way using django-simple-history, just like we did previously with the concept map fields
