### ISSUE TITLE
implement logging/tracking of data table curation history

### ISSUE THREAD

**Issue by stripathy** [neuroelectro/neuroelectro_org#62]
implementation will require deciding between implementing in mysql DB vs parsing text log files

**Comment by stripathy** [comment]
implementing historical models will take a bit of a code re-write, since they instantiate a new historical object on every model instance save.

e.g. the following can potentially generate 3 historical objects.

```python
            ncmOb = m.NeuronConceptMap.objects.get_or_create(ref_text = ref_text,
                                                          neuron = neuron_ob,
                                                          source = dsOb,
                                                          dt_id = box_id,
                                                          added_by = user)[0]
            if len(neuron_note) > 0:
                ncmOb.note = re.sub('_', ' ', neuron_note)
                ncmOb.save()
            if len(neuron_long_name) > 0:
                ncmOb.neuron_long_name = re.sub('_', ' ', neuron_long_name)
                ncmOb.save()
```

**Comment by stripathy** [comment]
since HistoricalRecord objects can easily track users (see: http://django-simple-history.readthedocs.org/en/latest/advanced.html#recording-which-user-changed-a-model), maybe we should change the validated_by field in concept_map objects to just a "changed_by" field, and let the historicalrecord object do the tracking of who made changes to each instance?

**Comment by stripathy** [comment]
Here's the current code for the ConceptMap model field:

```python
class ConceptMap(models.Model):
    class Meta:
        abstract = True    
    source = models.ForeignKey('DataSource')
    ref_text = models.CharField(max_length=200, null = True)
    match_quality = models.IntegerField(null = True)
    dt_id = models.CharField(max_length=20, null = True)
    date_mod = models.DateTimeField(blank = False, auto_now = True)
    added_by = models.ForeignKey('User', null = True) # user who first added the concept map
    validated_by = models.ManyToManyField('UserValidation', null=True)
    times_validated = models.IntegerField(default = 0)
    note = models.CharField(max_length=200, null = True) # this is a curation note
```

I think if that by implementing the ```HistoricalRecords``` class, we can change the ```added_by``` field to a ```changed_by``` field and then remove the ```validated_by``` field and let the historical records to the tracking.

**Comment by stripathy** [comment]
To implement this feature on a production database:
```pip install django-simple-history```

1. run terminal command to output json for user validation fields on concept map objects: ```python manage.py dumpdata neuroelectro.neuronconceptmap neuroelectro.ephysconceptmap neuroelectro.neuronephysdatamap neuroelectro.expfactconceptmap neuroelectro.user neuroelectro.uservalidation --indent 2  > concept_map_dump.json```
2. migrate the database: ```python manage.py migrate --fake-initial```
3. auto load the history fields: ```python manage.py populate_history --auto```
4. run the dbrestore command to restore the history fields in the django python shell ```
```python
import dbrestore
dbrestore.update_concept_map_histories()
```

**Comment by stripathy** [comment]
need to remove user validation model field after restoring db fields after migration

**Comment by stripathy** [comment]
if a user changes a concept (i.e., marks RMP instead of Rin), should times_validated change? what about marking of a neuron type/subtype?

**Comment by stripathy** [comment]
there's a lot of old user accounts for me (SJT), I should harmonize these all to a single account

**Comment by rgerkin** [comment]
@stripathy If you are asking these kinds of questions about `times_validated`, it suggests that `times_validated` is probably not rich enough to be useful.  Validation should be an explicit thing, and editing/marking should be something different.
