### ISSUE TITLE
Upgrade Django to version 1.8.*

### ISSUE THREAD

**Issue by mgottl04** [neuroelectro/neuroelectro_org#69]

**Comment by stripathy** [comment]
I put some effort into this - upgrading to django>1.6 this is definitely not trivial...

We'll have to deal with south (what was used for DB schema migrations) being incorporated into the main django repo : this is a description for how to do this https://docs.djangoproject.com/en/1.8/topics/migrations/#upgrading-from-south

We may also have to reorgainze the project directory structure too.

**Comment by mgottl04** [comment]
Agreed, it may be a good idea for all of us to do some reading and meet regarding whether we can feasibly do this and if so how to break it down.

**Comment by stripathy** [comment]
This issue : https://code.djangoproject.com/ticket/22280 can be fixed by removing the __init__.py from the base neuroelectro_org directory and then changing this line in settings.py from: 
```python
ROOT_URLCONF = 'neuroelectro_org.urls'
```
to 
```python
ROOT_URLCONF = 'neuroelectro.urls'
```

Unfortunately this then requires changing every internal url redirection in the neuroelectro html templates from "/neuroelectro/XXXX" to "/XXXX" but I dont think this is a bad thing per-se.

**Comment by stripathy** [comment]
@mgottl04 i have an beta version for this feature in this branch: https://github.com/neuroelectro/neuroelectro_org/tree/django1.8

A few things still need testing but should be ok for local developement.

**Comment by rgerkin** [comment]
Let me know if you need help with this one.  I've done the last several version upgrades for Django.

**Comment by stripathy** [comment]
Here's the workflow for updating to django1.8:

1. pull the django1.8 branch from the github repo and checkout
2. pip install django1.8 : sudo pip install django==1.8
3. apply the migrations: python manage.py migrate neuroelectro --fake-initial
You'll get prompted to remove the stale user field, say yes
4. check to make sure everything worked: python manage.py runserver
5. profit

**Comment by dtebaykin** [comment]
sudo pip install django-tastypie -U
sudo pip uninstall south
python manage.py migrate --fake-initial
python manage.py migrate neuroelectro --fake-initial (Say yes when prompted to remove stale fields)
