### ISSUE TITLE
Separate NeuroElectro_org into content required for site to run and everything else

### ISSUE THREAD

**Issue by rgerkin** [neuroelectro/neuroelectro_org#74]
@stripathy The code needed to run the site, on the server or locally, should be cleanly separated from the code used to locate papers, parse them, run various analyses, add new data, etc.  Only with the code needed to run (and read data from) the site compartmentalized will it be easy to pip install the site.  Also see #35.

**Comment by rgerkin** [comment]
@stripathy This is a blocking issue for me to do basically anything else for the site.  Do you have a plan for this?  If not, I can do it, but only if you're behind it.

**Comment by stripathy** [comment]
@rgerkin There's definitely pros for doing this and I'm all for better encapsulation of various pieces of neuroelectro (like text mining, the web app, data analysis). Can you take a look at what neurosynth does?  https://github.com/neurosynth The text mining is in the repo ACE and the core of the data analysis stuff is in neurosynth.

I think what most people want when doing 'pip install neuroelectro' isn't the ability to run the webapp in development or do any text mining, it's that they want the neuroelectro data and basic analyses they can do with it, right? If we can focus on a specific target, then we can separate that stuff (using API calls, spreadsheet download, etc.) from the rest of the gargantuan (and every growing) codebase.

**Comment by rgerkin** [comment]
@stripathy What do you think about this for a `pip install neuroelectro` goal:  

1) It installs a NeuroElectro python API.  That can be the stuff required to interact with the DB (i.e. django and other dependencies), and a subset of the analysis code (the well-tested, well-documented stuff).  That subset can be really tiny at first, and we can include more and more as stuff gets hardened.  

2a) The first (required) command is something like, "Download all the data locally", which downloads the database in its entirety, perhaps minus full texts.  I recommend actually just having a django data fixture created periodically by cron job so we don't have to worry about database compatibility.  The user isn't supposed to have to worry about concurrent writes, or schema updates, or anything like that, so that fixture is then used to generate an .sqlite database or something like that.  See [this](https://docs.djangoproject.com/en/1.8/howto/initial-data/) for details.  

or 

2b) The data never gets downloaded, instead we open the MYSQL server to the public, or maybe to people with some sort of API key access (how?) and they make calls just like you do, except they only have read-only access.  This is by far the easiest to maintain, but I don't know about security.  

or 

2c) Write the python API to map all django calls through the REST API and get all data via the REST API on the fly.  I don't think there's a generic Django back-end for this, and I don't know how to write one.  The only reason to do this is if we wanted to do lots of work and thought that our web server was fundamentally more secure than our MYSQL server.  

If this installation didn't actually serve webpages, then the object models can be considered distinct from the url.py and views.py and everything else, and those things should actually be in separate repositories from models.py which is kind of weird.

**Comment by rgerkin** [comment]
See progress on this in the [pypi branch](https://github.com/neuroelectro/neuroelectro_org/tree/pypi).

**Comment by rgerkin** [comment]
Completed with #55.
