### ISSUE TITLE
Ability to mark a DataTable as not related to NeuroElectro

### ISSUE THREAD

**Issue by dtebaykin** [neuroelectro/neuroelectro_org#80]
Consider adding a field to the DataTable model, a text or a boolean that would mark the datatable as not containing any electrophysiology information and removing all automatic annotations and removing it from the to-be-curated list.

**Comment by stripathy** [comment]
this table is a good example: only includes data from pharmacological conditions: http://dev.neuroelectro.org/data_table/712/
